vcftool/config/routes.rb
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  # Add future routes here
  # Add route for OmniAuth callback
  match '/auth/:provider/callback', to: 'auth#callback', via: %i[get post]
  get 'auth/signout'
  get 'contacts', to: 'contacts#index'
  get 'contacts/next'
  get 'contacts/prev'
  get 'contacts/reset'
  get 'contacts/edit/:id', to: 'contacts#edit', as: 'contacts_edit'
  post 'contacts/update/:id', to: 'contacts#update', as: 'contacts_update'
  get 'contacts/download'
  get 'contacts/new'
  post 'contacts/new'
  post 'contacts/create'
end

vcftool/app/views/layouts/application.html.erb
<!-- Copyright (c) Microsoft Corporation.
     Licensed under the MIT License. -->

<!DOCTYPE html>
<html>
  <head>
    <title>Outlook Contacts VCF Tool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container">
        <%= link_to "Outlook Contacts VCF Tool", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
          aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <% if @user_name %>
            <li class="nav-item">
              <%= link_to "New contact", contacts_new_path, class: "nav-link" %>
            </li>
            <% end %>
          </ul>
          <ul class="navbar-nav justify-content-end">
            <% if @user_name %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                  <% if @user_avatar %>
                    <img src=<%= @user_avatar %> class="rounded-circle align-self-center mr-2" style="width: 32px;">
                  <% else %>
                    <span class="badge badge-light"><%= @user_initials %></span>
                  <% end %>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <h5 class="dropdown-item-text mb-0"><%= @user_name %></h5>
                  <p class="dropdown-item-text text-muted mb-0"><%= @user_email %></p>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Sign Out", {:controller => :auth, :action => :signout}, :class => "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign in", "/auth/microsoft_graph_auth", method: :post, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <main role="main" class="container">
      <% unless flash.alert.nil? %>
        <div class="alert alert-danger alert-dismissable fade show" role="alert">
          <% if flash.alert.is_a?(Hash)%>
            <p class="mb-3"><%= flash.alert[:message] %></p>
            <% if flash.alert[:debug] %>
              <pre class="alert-pre border bg-light p-2"><code><%= flash.alert[:debug] %></code></pre>
            <% end %>
          <% else %>
            <%= flash.alert %>
          <% end %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <% unless flash.notice.nil? %>
        <div class="alert alert-success alert-dismissable fade show" role="alert">
          <% if flash.notice.is_a?(Hash)%>
            <p class="mb-3"><%= flash.notice[:message] %></p>
            <% if flash.notice[:debug] %>
              <pre class="alert-pre border bg-light p-2"><code><%= flash.notice[:debug] %></code></pre>
            <% end %>
          <% else %>
            <%= flash.notice %>
          <% end %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </main>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"></script>
    <%= yield :scripts %>
  </body>
</html>