vcftool/config/routes.rb
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  # Add future routes here
  # Add route for OmniAuth callback
  match '/auth/:provider/callback', to: 'auth#callback', via: %i[get post]
  get 'auth/signout'
  get 'contacts', to: 'contacts#index'
  get 'contacts/next'
  get 'contacts/prev'
  get 'contacts/reset'
  get 'contacts/edit/:id', to: 'contacts#edit', as: 'contacts_edit'
  post 'contacts/update/:id', to: 'contacts#update', as: 'contacts_update'
  get 'contacts/download'
  get 'contacts/new'
  post 'contacts/new'
  post 'contacts/create'
end

vcftool/app/controllers/contacts_controller.rb
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# frozen_string_literal: true

# ContactsController
class ContactsController < ApplicationController
  include GraphHelper
  include VcardHelper
  include ContactsHelper

  before_action :require_token

  def require_token
    redirect_to root_path if access_token.nil?
  end

  def index
    @back_disabled = session[:current_page].nil?

    @contacts = get_contacts access_token, session[:current_page]

    session[:next_page] = @contacts['@odata.nextLink']
  end

  def next
    push_prev_page session[:current_page]
    session[:current_page] = session[:next_page]
    redirect_to contacts_path
  end

  def prev
    prev_page = pop_prev_page
    prev_page = nil if prev_page&.empty?
    session[:current_page] = prev_page
    redirect_to contacts_path
  end

  def reset
    session.delete :prev_pages
    session.delete :current_page
    session.delete :next_page
    redirect_to contacts_path
  end

  def edit
    @contact = get_contact access_token, params[:id]
    @vcard = graph_to_vcard @contact
  end

  def download
    contact = get_contact access_token, params[:id]
    vcard = graph_to_vcard contact

    send_data vcard, filename: "#{contact['displayName'] || 'contact'}.vcf"
  end

  def update
    error = update_from_vcard params[:vcard], params[:id]

    unless error.nil?
      redirect_to contacts_edit_path(params[:id]), alert: error
      return
    end

    redirect_to contacts_path, notice: 'Contact updated'
  end

  def create
    if params[:vcard].nil?
      redirect_to contacts_new_path, alert: 'Could not parse vCard.'
      return
    end

    contacts = vcard_to_graph params[:vcard]

    create_contacts contacts
  end

  def create_contacts(contacts)
    errors = []
    contacts.each do |contact|
      response = create_contact access_token, contact
      errors.push check_api_response(response)
    end

    alert = alert_from_errors errors

    redirect_to contacts_path,
                alert: alert,
                notice: ("Created #{contacts.length} contacts" if alert.nil?)
  end

  def update_from_vcard(card, id)
    contacts = vcard_to_graph(card)
    error = check_result contacts
    return error unless error.nil?

    apiresponse = update_contact access_token, id, contacts.first
    check_api_response apiresponse
  end

  def push_prev_page(prev_page)
    prev_pages = session[:prev_pages]
    prev_pages = [] if prev_pages.nil?
    prev_pages.push prev_page || ''
    session[:prev_pages] = prev_pages
  end

  def pop_prev_page
    prev_pages = session[:prev_pages]
    prev_pages&.pop
  end
end

vcftool/app/helpers/contacts_helper.rb
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# frozen_string_literal: true

# ContactsHelper
module ContactsHelper
  def check_api_response(response)
    return if response.nil?

    return unless response.key? 'error'

    {
      message: response['error']['message'],
      debug: response.to_json
    }
  end

  def check_result(contacts)
    'The vCard text could not be parsed.' if contacts.nil?

    'The vCard text must contain only one contact.' if contacts.length > 1
  end

  def alert_from_errors(errors)
    return unless errors.any?

    debugitems = []
    errors.each do |error|
      debugitems.push error unless error.nil?
    end

    {
      message: "#{debugitems.length} errors encountered when creating contacts",
      debug: debugitems.to_json
    }
  end
end

vcftool/app/views/contacts/_contact_card.html.erb
<!-- Copyright (c) Microsoft Corporation.
     Licensed under the MIT License. -->

<div class="col mb-4">
  <div class="card h-100">
    <div class="card-body">
      <h5 class="card-title"><%= contact['displayName'] %></h5>
      <%= link_to "Edit", contacts_edit_path(id: contact['id']), class: "btn btn-primary" %>
      <%= link_to "Download", contacts_download_path(id: contact['id']), class: "btn btn-primary" %>
    </div>
  </div>
</div>

vcftool/app/views/contacts/edit.html.erb
<!-- Copyright (c) Microsoft Corporation.
     Licensed under the MIT License. -->

<%= form_with(url: contacts_update_path(id: @contact['id'])) do %>
  <div class="row">
    <div class="col-md-8">
      <h1 class="mb-3"><%= @contact['displayName'] %></h1>
    </div>
    <div class="col-md-4 d-md-flex flex-row-reverse align-items-center">
      <%= submit_tag "Update", class: "btn btn-primary mb-3" %>
    </div>
  </div>
  <%= text_area_tag "vcard", @vcard, class: "form-control mb-3", rows: @vcard.to_s.lines.count+1 %>
<% end %>

vcftool/app/views/contacts/index.html.erb
<!-- Copyright (c) Microsoft Corporation.
     Licensed under the MIT License. -->

<h1>Contacts</h1>
<nav>
  <ul class="pagination">
    <li class="<%= @back_disabled ? "page-item disabled" : "page-item" %>">
      <%= link_to "Beginning", contacts_reset_path, class: "page-link" %>
    </li>
    <li class="<%= @back_disabled ? "page-item disabled" : "page-item" %>">
      <%= link_to "Previous", contacts_prev_path, class: "page-link" %>
    </li>
    <li class="<%= @contacts['@odata.nextLink'].nil? ? "page-item disabled" : "page-item" %>">
      <%= link_to "Next", contacts_next_path, class: "page-link" %>
    </li>
  </ul>
</nav>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
  <% @contacts['value'].each do |contact| %>
    <%= render partial: 'contact_card', locals: { contact: contact } %>
  <% end %>
</div>

vcftool/app/views/contacts/new.html.erb
<!-- Copyright (c) Microsoft Corporation.
     Licensed under the MIT License. -->

<h1 class="mb-3">New contact</h1>
<div class="custom-file text-truncate">
  <%= file_field_tag "vcf", accept: "text/vcard,text/x-vcard", class: "custom-file-input" %>
  <%= label_tag "vcf", "Choose file or enter text below", class: "custom-file-label" %>
</div>
<%= form_with url: contacts_create_path do %>
  <%= text_area_tag "vcard", @vcard, class: "form-control mb-3", rows: 20, required:true %>
  <%= submit_tag "Create", class: "btn btn-primary" %>
  <%= link_to "Cancel", root_path, class: "btn btn-secondary" %>
<% end %>
<%= content_for :scripts do %>
  <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
  <script>
    // Initialize Bootstrap custom file input
    $(document).ready(function () {
      bsCustomFileInput.init();

      $('#vcf').change(loadFile);
    });

    function loadFile(evt) {
      var file = evt.target.files[0];

      if (file) {
        if (!file.type.match('.*vcard')) {
          return;
        }

        var reader = new FileReader();

        reader.onload = (function(fileContents) {
          return function(e) {
            $('#vcard').val(e.target.result);
          };
        })(file);

        reader.readAsText(file);
      }
    }
  </script>
<% end %>